# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'eats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eats
  pod 'pop', '1.0.10'
  pod "YelpAPI"
  pod 'Firebase/Core'

end
