# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Swipeable-View-Stack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swipeable-View-Stack
  pod 'pop', '1.0.10'
  pod "YelpAPI"
  pod 'CDYelpFusionKit', '1.5.0'
  pod 'Firebase/Core'
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'ObjectMapper', '~> 3.1'
  pod 'Alamofire', '~> 4.6'
end
